FROM emingdgn/g04-frontend:latest as vue-app

FROM nginx:1.27.2-alpine
COPY --from=vue-app /app/target/classes/static /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]