FROM localhost:5000/frontend:1.0 as vue-app

FROM nginx:1.27.2-alpine
COPY --from=vue-app /app/target/classes/static /usr/share/nginx/html
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]